package com.textile.model;
// Generated Apr 3, 2017 2:59:45 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * ChildQuality generated by hbm2java
 */
public class ChildQuality  implements java.io.Serializable {


     private Integer idl;
     private ParentQuality parentQuality;
     private String machines;
     private Integer count;
     private Float countmaintained;
     private Float csp;
     private Float cv;
     private Float strengthCv;
     private Float minus50EveryDay;
     private Float plus50EveryDay;
     private Float plus280everyDay;
     private Float ipi;
     private String remarks;
     private Date actualDate;

    public ChildQuality() {
    }

    public ChildQuality(ParentQuality parentQuality, String machines, Integer count, Float countmaintained, Float csp, Float cv, Float strengthCv, Float minus50EveryDay, Float plus50EveryDay, Float plus280everyDay, Float ipi, String remarks, Date actualDate) {
       this.parentQuality = parentQuality;
       this.machines = machines;
       this.count = count;
       this.countmaintained = countmaintained;
       this.csp = csp;
       this.cv = cv;
       this.strengthCv = strengthCv;
       this.minus50EveryDay = minus50EveryDay;
       this.plus50EveryDay = plus50EveryDay;
       this.plus280everyDay = plus280everyDay;
       this.ipi = ipi;
       this.remarks = remarks;
       this.actualDate = actualDate;
    }
   
    public Integer getIdl() {
        return this.idl;
    }
    
    public void setIdl(Integer idl) {
        this.idl = idl;
    }
    public ParentQuality getParentQuality() {
        return this.parentQuality;
    }
    
    public void setParentQuality(ParentQuality parentQuality) {
        this.parentQuality = parentQuality;
    }
    public String getMachines() {
        return this.machines;
    }
    
    public void setMachines(String machines) {
        this.machines = machines;
    }
    public Integer getCount() {
        return this.count;
    }
    
    public void setCount(Integer count) {
        this.count = count;
    }
    public Float getCountmaintained() {
        return this.countmaintained;
    }
    
    public void setCountmaintained(Float countmaintained) {
        this.countmaintained = countmaintained;
    }
    public Float getCsp() {
        return this.csp;
    }
    
    public void setCsp(Float csp) {
        this.csp = csp;
    }
    public Float getCv() {
        return this.cv;
    }
    
    public void setCv(Float cv) {
        this.cv = cv;
    }
    public Float getStrengthCv() {
        return this.strengthCv;
    }
    
    public void setStrengthCv(Float strengthCv) {
        this.strengthCv = strengthCv;
    }
    public Float getMinus50EveryDay() {
        return this.minus50EveryDay;
    }
    
    public void setMinus50EveryDay(Float minus50EveryDay) {
        this.minus50EveryDay = minus50EveryDay;
    }
    public Float getPlus50EveryDay() {
        return this.plus50EveryDay;
    }
    
    public void setPlus50EveryDay(Float plus50EveryDay) {
        this.plus50EveryDay = plus50EveryDay;
    }
    public Float getPlus280everyDay() {
        return this.plus280everyDay;
    }
    
    public void setPlus280everyDay(Float plus280everyDay) {
        this.plus280everyDay = plus280everyDay;
    }
    public Float getIpi() {
        return this.ipi;
    }
    
    public void setIpi(Float ipi) {
        this.ipi = ipi;
    }
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }
    public Date getActualDate() {
        return this.actualDate;
    }
    
    public void setActualDate(Date actualDate) {
        this.actualDate = actualDate;
    }




}


