package com.textile.model;
// Generated Apr 1, 2017 4:28:55 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * ChildPacking generated by hbm2java
 */
public class ChildPacking  implements java.io.Serializable {


     private Integer idp;
     private ParentPacking parentPacking;
     private String count;
     private Integer countDb;
     private String boxType;
     private String weight;
     private Float openingStock;
     private Float packedBags;
     private Float noofKgsPacked;
     private Float dispatch;
     private Float disclose;
     private Date cdate;
     private Date actualDate;
     private String CClose;

    public ChildPacking() {
    }

    public ChildPacking(ParentPacking parentPacking, String count, Integer countDb, String boxType, String weight, Float openingStock, Float packedBags,Float noofKgsPacked, Float dispatch, Float disclose, Date cdate, Date actualDate, String CClose) {
       this.parentPacking = parentPacking;
       this.count = count;
       this.countDb = countDb;
       this.boxType = boxType;
       this.weight = weight;
       this.openingStock = openingStock;
       this.packedBags = packedBags;
       this.noofKgsPacked=noofKgsPacked;
       this.dispatch = dispatch;
       this.disclose = disclose;
       this.cdate = cdate;
       this.actualDate = actualDate;
       this.CClose = CClose;
    }
   
    public Integer getIdp() {
        return this.idp;
    }
    
    public void setIdp(Integer idp) {
        this.idp = idp;
    }
    public ParentPacking getParentPacking() {
        return this.parentPacking;
    }
    
    public void setParentPacking(ParentPacking parentPacking) {
        this.parentPacking = parentPacking;
    }
    public String getCount() {
        return this.count;
    }
    
    public void setCount(String count) {
        this.count = count;
    }
    public Integer getCountDb() {
        return this.countDb;
    }
    
    public void setCountDb(Integer countDb) {
        this.countDb = countDb;
    }
    public String getBoxType() {
        return this.boxType;
    }
    
    public void setBoxType(String boxType) {
        this.boxType = boxType;
    }
    public String getWeight() {
        return this.weight;
    }
    
    public void setWeight(String weight) {
        this.weight = weight;
    }
    public Float getOpeningStock() {
        return this.openingStock;
    }
    
    public void setOpeningStock(Float openingStock) {
        this.openingStock = openingStock;
    }
    public Float getPackedBags() {
        return this.packedBags;
    }
    
    public void setPackedBags(Float packedBags) {
        this.packedBags = packedBags;
    }

    public Float getNoofKgsPacked() {
        return noofKgsPacked;
    }

    public void setNoofKgsPacked(Float noofKgsPacked) {
        this.noofKgsPacked = noofKgsPacked;
    }
    
    public Float getDispatch() {
        return this.dispatch;
    }
    
    public void setDispatch(Float dispatch) {
        this.dispatch = dispatch;
    }
    public Float getDisclose() {
        return this.disclose;
    }
    
    public void setDisclose(Float disclose) {
        this.disclose = disclose;
    }
    public Date getCdate() {
        return this.cdate;
    }
    
    public void setCdate(Date cdate) {
        this.cdate = cdate;
    }
    public Date getActualDate() {
        return this.actualDate;
    }
    
    public void setActualDate(Date actualDate) {
        this.actualDate = actualDate;
    }

    public String getCClose() {
        return CClose;
    }

    public void setCClose(String CClose) {
        this.CClose = CClose;
    }
   



}


