package com.textile.model;
// Generated Apr 3, 2017 2:59:45 PM by Hibernate Tools 4.3.1

import java.util.Date;




/**
 * ChildOpenend generated by hbm2java
 */
public class ChildOpenend  implements java.io.Serializable {


     private Integer idp;
     private ParentOpenend parentOpenend;
     private String openEnd;
     private Integer count;
     private Float countMaintain;
     private Double mcSpeed;
     private Float tm;
     private Double mcRunning;
     private Float expectedProduction;
     private Float actualProduction;
     private Float efficiency;
     private String breakeges;
     private Float hundredPercentEfcy;
     private String remarks;
     private Integer empId;
     private Date actualDate;

    public Date getActualDate() {
        return actualDate;
    }

    public void setActualDate(Date actualDate) {
        this.actualDate = actualDate;
    }

    public ChildOpenend() {
    }

    public ChildOpenend(ParentOpenend parentOpenend, String openEnd, Integer count, Float countMaintain, Double mcSpeed, Float tm, Double mcRunning, Float expectedProduction, Float actualProduction, Float efficiency, String breakeges, Float hundredPercentEfcy, String remarks, Integer empId,Date actualDate) {
       this.parentOpenend = parentOpenend;
       this.openEnd = openEnd;
       this.count = count;
       this.countMaintain = countMaintain;
       this.mcSpeed = mcSpeed;
       this.tm = tm;
       this.mcRunning = mcRunning;
       this.expectedProduction = expectedProduction;
       this.actualProduction = actualProduction;
       this.efficiency = efficiency;
       this.breakeges = breakeges;
       this.hundredPercentEfcy = hundredPercentEfcy;
       this.remarks = remarks;
       this.empId = empId;
       this.actualDate=actualDate;
    }
   
    public Integer getIdp() {
        return this.idp;
    }
    
    public void setIdp(Integer idp) {
        this.idp = idp;
    }
    public ParentOpenend getParentOpenend() {
        return this.parentOpenend;
    }
    
    public void setParentOpenend(ParentOpenend parentOpenend) {
        this.parentOpenend = parentOpenend;
    }
    public String getOpenEnd() {
        return this.openEnd;
    }
    
    public void setOpenEnd(String openEnd) {
        this.openEnd = openEnd;
    }
    public Integer getCount() {
        return this.count;
    }
    
    public void setCount(Integer count) {
        this.count = count;
    }
    public Float getCountMaintain() {
        return this.countMaintain;
    }
    
    public void setCountMaintain(Float countMaintain) {
        this.countMaintain = countMaintain;
    }
    public Double getMcSpeed() {
        return this.mcSpeed;
    }
    
    public void setMcSpeed(Double mcSpeed) {
        this.mcSpeed = mcSpeed;
    }
    public Float getTm() {
        return this.tm;
    }
    
    public void setTm(Float tm) {
        this.tm = tm;
    }
    public Double getMcRunning() {
        return this.mcRunning;
    }
    
    public void setMcRunning(Double mcRunning) {
        this.mcRunning = mcRunning;
    }
    public Float getExpectedProduction() {
        return this.expectedProduction;
    }
    
    public void setExpectedProduction(Float expectedProduction) {
        this.expectedProduction = expectedProduction;
    }
    public Float getActualProduction() {
        return this.actualProduction;
    }
    
    public void setActualProduction(Float actualProduction) {
        this.actualProduction = actualProduction;
    }
    public Float getEfficiency() {
        return this.efficiency;
    }
    
    public void setEfficiency(Float efficiency) {
        this.efficiency = efficiency;
    }
    public String getBreakeges() {
        return this.breakeges;
    }
    
    public void setBreakeges(String breakeges) {
        this.breakeges = breakeges;
    }
    public Float getHundredPercentEfcy() {
        return this.hundredPercentEfcy;
    }
    
    public void setHundredPercentEfcy(Float hundredPercentEfcy) {
        this.hundredPercentEfcy = hundredPercentEfcy;
    }
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }
    public Integer getEmpId() {
        return this.empId;
    }
    
    public void setEmpId(Integer empId) {
        this.empId = empId;
    }




}


