package com.textile.model;
// Generated Apr 3, 2017 2:59:45 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * ChildGdPrecleaning generated by hbm2java
 */
public class ChildGdPrecleaning  implements java.io.Serializable {


     private Integer idp;
     private ParentGdPrecleaning parentGdPrecleaning;
     private String variety;
     private Float weight;
     private Float mixing;
     private Float totalBales;
     private Date actualDate;

    public ChildGdPrecleaning() {
    }

    public ChildGdPrecleaning(ParentGdPrecleaning parentGdPrecleaning, String variety, Float weight, Float mixing, Float totalBales, Date actualDate) {
       this.parentGdPrecleaning = parentGdPrecleaning;
       this.variety = variety;
       this.weight = weight;
       this.mixing = mixing;
       this.totalBales = totalBales;
       this.actualDate = actualDate;
    }
   
    public Integer getIdp() {
        return this.idp;
    }
    
    public void setIdp(Integer idp) {
        this.idp = idp;
    }
    public ParentGdPrecleaning getParentGdPrecleaning() {
        return this.parentGdPrecleaning;
    }
    
    public void setParentGdPrecleaning(ParentGdPrecleaning parentGdPrecleaning) {
        this.parentGdPrecleaning = parentGdPrecleaning;
    }
    public String getVariety() {
        return this.variety;
    }
    
    public void setVariety(String variety) {
        this.variety = variety;
    }
    public Float getWeight() {
        return this.weight;
    }
    
    public void setWeight(Float weight) {
        this.weight = weight;
    }
    public Float getMixing() {
        return this.mixing;
    }
    
    public void setMixing(Float mixing) {
        this.mixing = mixing;
    }
    public Float getTotalBales() {
        return this.totalBales;
    }
    
    public void setTotalBales(Float totalBales) {
        this.totalBales = totalBales;
    }
    public Date getActualDate() {
        return this.actualDate;
    }
    
    public void setActualDate(Date actualDate) {
        this.actualDate = actualDate;
    }




}


