package com.textile.model;
// Generated Apr 3, 2017 2:59:45 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * ChildGdProduction generated by hbm2java
 */
public class ChildGdProduction  implements java.io.Serializable {


     private Integer idp;
     private ParentGdProduction parentGdProduction;
     private String variety;
     private Float weight;
     private Float mixing;
     private Float totalBales;
     private Date actualDate;

    public ChildGdProduction() {
    }

    public ChildGdProduction(ParentGdProduction parentGdProduction, String variety, Float weight, Float mixing, Float totalBales, Date actualDate) {
       this.parentGdProduction = parentGdProduction;
       this.variety = variety;
       this.weight = weight;
       this.mixing = mixing;
       this.totalBales = totalBales;
       this.actualDate = actualDate;
    }
   
    public Integer getIdp() {
        return this.idp;
    }
    
    public void setIdp(Integer idp) {
        this.idp = idp;
    }
    public ParentGdProduction getParentGdProduction() {
        return this.parentGdProduction;
    }
    
    public void setParentGdProduction(ParentGdProduction parentGdProduction) {
        this.parentGdProduction = parentGdProduction;
    }
    public String getVariety() {
        return this.variety;
    }
    
    public void setVariety(String variety) {
        this.variety = variety;
    }
    public Float getWeight() {
        return this.weight;
    }
    
    public void setWeight(Float weight) {
        this.weight = weight;
    }
    public Float getMixing() {
        return this.mixing;
    }
    
    public void setMixing(Float mixing) {
        this.mixing = mixing;
    }
    public Float getTotalBales() {
        return this.totalBales;
    }
    
    public void setTotalBales(Float totalBales) {
        this.totalBales = totalBales;
    }
    public Date getActualDate() {
        return this.actualDate;
    }
    
    public void setActualDate(Date actualDate) {
        this.actualDate = actualDate;
    }




}


