package com.textile.model;
// Generated Apr 3, 2017 2:59:45 PM by Hibernate Tools 4.3.1



/**
 * ChildDrawing generated by hbm2java
 */
public class ChildDrawing  implements java.io.Serializable {


     private Integer idp;
     private ParentDrawing parentDrawing;
     private String carding;
     private Float deliveryHank;
     private Float mcSpeed;
     private Float mcRunning;
     private Float expectedProduction;
     private Float actualProduction;
     private Float efficiency;
     private String breakedInShifts;
     private String remarks;
     private Integer empId;

    public ChildDrawing() {
    }

    public ChildDrawing(ParentDrawing parentDrawing, String carding, Float deliveryHank, Float mcSpeed, Float mcRunning, Float expectedProduction, Float actualProduction, Float efficiency, String breakedInShifts, String remarks, Integer empId) {
       this.parentDrawing = parentDrawing;
       this.carding = carding;
       this.deliveryHank = deliveryHank;
       this.mcSpeed = mcSpeed;
       this.mcRunning = mcRunning;
       this.expectedProduction = expectedProduction;
       this.actualProduction = actualProduction;
       this.efficiency = efficiency;
       this.breakedInShifts = breakedInShifts;
       this.remarks = remarks;
       this.empId = empId;
    }
   
    public Integer getIdp() {
        return this.idp;
    }
    
    public void setIdp(Integer idp) {
        this.idp = idp;
    }
    public ParentDrawing getParentDrawing() {
        return this.parentDrawing;
    }
    
    public void setParentDrawing(ParentDrawing parentDrawing) {
        this.parentDrawing = parentDrawing;
    }
    public String getCarding() {
        return this.carding;
    }
    
    public void setCarding(String carding) {
        this.carding = carding;
    }
    public Float getDeliveryHank() {
        return this.deliveryHank;
    }
    
    public void setDeliveryHank(Float deliveryHank) {
        this.deliveryHank = deliveryHank;
    }
    public Float getMcSpeed() {
        return this.mcSpeed;
    }
    
    public void setMcSpeed(Float mcSpeed) {
        this.mcSpeed = mcSpeed;
    }
    public Float getMcRunning() {
        return this.mcRunning;
    }
    
    public void setMcRunning(Float mcRunning) {
        this.mcRunning = mcRunning;
    }
    public Float getExpectedProduction() {
        return this.expectedProduction;
    }
    
    public void setExpectedProduction(Float expectedProduction) {
        this.expectedProduction = expectedProduction;
    }
    public Float getActualProduction() {
        return this.actualProduction;
    }
    
    public void setActualProduction(Float actualProduction) {
        this.actualProduction = actualProduction;
    }
    public Float getEfficiency() {
        return this.efficiency;
    }
    
    public void setEfficiency(Float efficiency) {
        this.efficiency = efficiency;
    }
    public String getBreakedInShifts() {
        return this.breakedInShifts;
    }
    
    public void setBreakedInShifts(String breakedInShifts) {
        this.breakedInShifts = breakedInShifts;
    }
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }
    public Integer getEmpId() {
        return this.empId;
    }
    
    public void setEmpId(Integer empId) {
        this.empId = empId;
    }




}


