package com.textile.model;
// Generated Apr 3, 2017 2:59:45 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * ChildGdWastage generated by hbm2java
 */
public class ChildGdWastage  implements java.io.Serializable {


     private Integer idp;
     private ParentGdWastage parentGdWastage;
     private String variety;
     private Float numberofBales;
     private Float weight;
     private Date actDate;

    public ChildGdWastage() {
    }

    public ChildGdWastage(ParentGdWastage parentGdWastage, String variety, Float numberofBales, Float weight, Date actDate) {
       this.parentGdWastage = parentGdWastage;
       this.variety = variety;
       this.numberofBales = numberofBales;
       this.weight = weight;
       this.actDate = actDate;
    }
   
    public Integer getIdp() {
        return this.idp;
    }
    
    public void setIdp(Integer idp) {
        this.idp = idp;
    }
    public ParentGdWastage getParentGdWastage() {
        return this.parentGdWastage;
    }
    
    public void setParentGdWastage(ParentGdWastage parentGdWastage) {
        this.parentGdWastage = parentGdWastage;
    }
    public String getVariety() {
        return this.variety;
    }
    
    public void setVariety(String variety) {
        this.variety = variety;
    }
    public Float getNumberofBales() {
        return this.numberofBales;
    }
    
    public void setNumberofBales(Float numberofBales) {
        this.numberofBales = numberofBales;
    }
    public Float getWeight() {
        return this.weight;
    }
    
    public void setWeight(Float weight) {
        this.weight = weight;
    }
    public Date getActDate() {
        return this.actDate;
    }
    
    public void setActDate(Date actDate) {
        this.actDate = actDate;
    }




}


