package com.textile.model;
// Generated Apr 3, 2017 2:59:45 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * FinancialYearBackup generated by hbm2java
 */
public class FinancialYearBackup  implements java.io.Serializable {


     private Integer idf;
     private Date yearendDate;
     private Date backupDate;

    public FinancialYearBackup() {
    }

    public FinancialYearBackup(Date yearendDate, Date backupDate) {
       this.yearendDate = yearendDate;
       this.backupDate = backupDate;
    }
   
    public Integer getIdf() {
        return this.idf;
    }
    
    public void setIdf(Integer idf) {
        this.idf = idf;
    }
    public Date getYearendDate() {
        return this.yearendDate;
    }
    
    public void setYearendDate(Date yearendDate) {
        this.yearendDate = yearendDate;
    }
    public Date getBackupDate() {
        return this.backupDate;
    }
    
    public void setBackupDate(Date backupDate) {
        this.backupDate = backupDate;
    }




}


