package com.textile.model;
// Generated Apr 3, 2017 2:59:45 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * GdSale generated by hbm2java
 */
public class GdSale  implements java.io.Serializable {


     private Integer ids;
     private Date date;
     private String customerName;
     private String productType;
     private Float noOfBales;
     private Float grossWeight;
     private Float netWeight;
     private Float tareWeight;
     private String vehicleNo;
     private String remarks;
     private Integer noOfKgs;

    public GdSale() {
    }

    public GdSale(Date date, String customerName, String productType, Float noOfBales, Float grossWeight, Float netWeight, Float tareWeight, String vehicleNo, String remarks, Integer noOfKgs) {
       this.date = date;
       this.customerName = customerName;
       this.productType = productType;
       this.noOfBales = noOfBales;
       this.grossWeight = grossWeight;
       this.netWeight = netWeight;
       this.tareWeight = tareWeight;
       this.vehicleNo = vehicleNo;
       this.remarks = remarks;
       this.noOfKgs = noOfKgs;
    }
   
    public Integer getIds() {
        return this.ids;
    }
    
    public void setIds(Integer ids) {
        this.ids = ids;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public String getCustomerName() {
        return this.customerName;
    }
    
    public void setCustomerName(String customerName) {
        this.customerName = customerName;
    }
    public String getProductType() {
        return this.productType;
    }
    
    public void setProductType(String productType) {
        this.productType = productType;
    }
    public Float getNoOfBales() {
        return this.noOfBales;
    }
    
    public void setNoOfBales(Float noOfBales) {
        this.noOfBales = noOfBales;
    }
    public Float getGrossWeight() {
        return this.grossWeight;
    }
    
    public void setGrossWeight(Float grossWeight) {
        this.grossWeight = grossWeight;
    }
    public Float getNetWeight() {
        return this.netWeight;
    }
    
    public void setNetWeight(Float netWeight) {
        this.netWeight = netWeight;
    }
    public Float getTareWeight() {
        return this.tareWeight;
    }
    
    public void setTareWeight(Float tareWeight) {
        this.tareWeight = tareWeight;
    }
    public String getVehicleNo() {
        return this.vehicleNo;
    }
    
    public void setVehicleNo(String vehicleNo) {
        this.vehicleNo = vehicleNo;
    }
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }
    public Integer getNoOfKgs() {
        return this.noOfKgs;
    }
    
    public void setNoOfKgs(Integer noOfKgs) {
        this.noOfKgs = noOfKgs;
    }




}


