package com.textile.model;
// Generated Apr 3, 2017 2:59:45 PM by Hibernate Tools 4.3.1



/**
 * Login generated by hbm2java
 */
public class Login  implements java.io.Serializable {


     private Integer id;
     private String userName;
     private String password;
     private String loginType;
     private String designation;
     private String partialType;

    public Login() {
    }

    public Login(String userName, String password, String loginType, String designation, String partialType) {
       this.userName = userName;
       this.password = password;
       this.loginType = loginType;
       this.designation = designation;
       this.partialType = partialType;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getLoginType() {
        return this.loginType;
    }
    
    public void setLoginType(String loginType) {
        this.loginType = loginType;
    }
    public String getDesignation() {
        return this.designation;
    }
    
    public void setDesignation(String designation) {
        this.designation = designation;
    }
    public String getPartialType() {
        return this.partialType;
    }
    
    public void setPartialType(String partialType) {
        this.partialType = partialType;
    }




}


