package com.textile.model;
// Generated Apr 3, 2017 2:59:45 PM by Hibernate Tools 4.3.1



/**
 * PackPatterns generated by hbm2java
 */
public class PackPatterns  implements java.io.Serializable {


     private Integer idp;
     private Float conWeight;
     private Float noOfCones;
     private Float weight;
     private Float tareWeight;
     private String typeOfPacking;

    public String getTypeOfPacking() {
        return typeOfPacking;
    }

    public void setTypeOfPacking(String typeOfPacking) {
        this.typeOfPacking = typeOfPacking;
    }

    public PackPatterns() {
    }

    public PackPatterns(Float conWeight, Float noOfCones, Float weight, Float tareWeight,String typeOfPacking) {
       this.conWeight = conWeight;
       this.noOfCones = noOfCones;
       this.weight = weight;
       this.tareWeight = tareWeight;
       this.typeOfPacking=typeOfPacking;
    }
   
    public Integer getIdp() {
        return this.idp;
    }
    
    public void setIdp(Integer idp) {
        this.idp = idp;
    }
    public Float getConWeight() {
        return this.conWeight;
    }
    
    public void setConWeight(Float conWeight) {
        this.conWeight = conWeight;
    }
    public Float getNoOfCones() {
        return this.noOfCones;
    }
    
    public void setNoOfCones(Float noOfCones) {
        this.noOfCones = noOfCones;
    }
    public Float getWeight() {
        return this.weight;
    }
    
    public void setWeight(Float weight) {
        this.weight = weight;
    }
    public Float getTareWeight() {
        return this.tareWeight;
    }
    
    public void setTareWeight(Float tareWeight) {
        this.tareWeight = tareWeight;
    }




}


