package com.textile.model;
// Generated Apr 1, 2017 4:28:55 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ParentPacking generated by hbm2java
 */
public class ParentPacking  implements java.io.Serializable {


     private Integer idpq;
     private Date date;
     private String supervisor;
     private String shifts;
     private String evocher;
     private Float totalOpeningStock;
     private Float totalPackedBags;
     private Float totalNoofkgsPacked;
     private Float totalDispatch;
     private Float totalDisclose;
     private Set childPackings = new HashSet(0);

    public ParentPacking() {
    }

    public ParentPacking(Date date, String supervisor, String shifts, String evocher, Float totalOpeningStock, Float totalPackedBags, Float totalNoofkgsPacked, Float totalDispatch, Float totalDisclose, Set childPackings) {
       this.date = date;
       this.supervisor = supervisor;
       this.shifts = shifts;
       this.evocher=evocher;
       this.totalOpeningStock = totalOpeningStock;
       this.totalPackedBags = totalPackedBags;
       this.totalNoofkgsPacked=totalNoofkgsPacked;
       this.totalDispatch = totalDispatch;
       this.totalDisclose = totalDisclose;
       this.childPackings = childPackings;
    }
   
    public Integer getIdpq() {
        return this.idpq;
    }
    
    public void setIdpq(Integer idpq) {
        this.idpq = idpq;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public String getSupervisor() {
        return this.supervisor;
    }
    
    public void setSupervisor(String supervisor) {
        this.supervisor = supervisor;
    }
    public String getShifts() {
        return this.shifts;
    }
    
    public void setShifts(String shifts) {
        this.shifts = shifts;
    }

    public String getEvocher() {
        return evocher;
    }

    public void setEvocher(String evocher) {
        this.evocher = evocher;
    }
    
    
    public Float getTotalOpeningStock() {
        return this.totalOpeningStock;
    }
    
    public void setTotalOpeningStock(Float totalOpeningStock) {
        this.totalOpeningStock = totalOpeningStock;
    }
    public Float getTotalPackedBags() {
        return this.totalPackedBags;
    }
    
    public void setTotalPackedBags(Float totalPackedBags) {
        this.totalPackedBags = totalPackedBags;
    }

    public Float getTotalNoofkgsPacked() {
        return totalNoofkgsPacked;
    }

    public void setTotalNoofkgsPacked(Float totalNoofkgsPacked) {
        this.totalNoofkgsPacked = totalNoofkgsPacked;
    }
    
    public Float getTotalDispatch() {
        return this.totalDispatch;
    }
    
    public void setTotalDispatch(Float totalDispatch) {
        this.totalDispatch = totalDispatch;
    }
    public Float getTotalDisclose() {
        return this.totalDisclose;
    }
    
    public void setTotalDisclose(Float totalDisclose) {
        this.totalDisclose = totalDisclose;
    }
    public Set getChildPackings() {
        return this.childPackings;
    }
    
    public void setChildPackings(Set childPackings) {
        this.childPackings = childPackings;
    }




}


