package com.textile.model;
// Generated Apr 3, 2017 2:59:45 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ParentOpenend generated by hbm2java
 */
public class ParentOpenend  implements java.io.Serializable {


     private Integer ido;
     private Date date;
     private String superviser;
     private String shifts;
     private Float totalEp;
     private Float totalAp;
     private Float totalEfcy;
     private String totalBreakeges;
     private Float totalHpEfcy;
     private Set childOpenends = new HashSet(0);

    public ParentOpenend() {
    }

    public ParentOpenend(Date date, String superviser, String shifts, Float totalEp, Float totalAp, Float totalEfcy, String totalBreakeges, Float totalHpEfcy, Set childOpenends) {
       this.date = date;
       this.superviser = superviser;
       this.shifts = shifts;
       this.totalEp = totalEp;
       this.totalAp = totalAp;
       this.totalEfcy = totalEfcy;
       this.totalBreakeges = totalBreakeges;
       this.totalHpEfcy = totalHpEfcy;
       this.childOpenends = childOpenends;
    }
   
    public Integer getIdo() {
        return this.ido;
    }
    
    public void setIdo(Integer ido) {
        this.ido = ido;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public String getSuperviser() {
        return this.superviser;
    }
    
    public void setSuperviser(String superviser) {
        this.superviser = superviser;
    }
    public String getShifts() {
        return this.shifts;
    }
    
    public void setShifts(String shifts) {
        this.shifts = shifts;
    }
    public Float getTotalEp() {
        return this.totalEp;
    }
    
    public void setTotalEp(Float totalEp) {
        this.totalEp = totalEp;
    }
    public Float getTotalAp() {
        return this.totalAp;
    }
    
    public void setTotalAp(Float totalAp) {
        this.totalAp = totalAp;
    }
    public Float getTotalEfcy() {
        return this.totalEfcy;
    }
    
    public void setTotalEfcy(Float totalEfcy) {
        this.totalEfcy = totalEfcy;
    }
    public String getTotalBreakeges() {
        return this.totalBreakeges;
    }
    
    public void setTotalBreakeges(String totalBreakeges) {
        this.totalBreakeges = totalBreakeges;
    }
    public Float getTotalHpEfcy() {
        return this.totalHpEfcy;
    }
    
    public void setTotalHpEfcy(Float totalHpEfcy) {
        this.totalHpEfcy = totalHpEfcy;
    }
    public Set getChildOpenends() {
        return this.childOpenends;
    }
    
    public void setChildOpenends(Set childOpenends) {
        this.childOpenends = childOpenends;
    }




}


