package com.textile.model;
// Generated Apr 3, 2017 2:59:45 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ParentQuality generated by hbm2java
 */
public class ParentQuality  implements java.io.Serializable {


     private Integer idq;
     private Superviser superviser;
     private Date date;
     private String superViser;
     private String shifts;
     private String testType;
     private Set childQualities = new HashSet(0);

    public ParentQuality() {
    }

    public ParentQuality(Superviser superviser, Date date, String superViser, String shifts, String testType, Set childQualities) {
       this.superviser = superviser;
       this.date = date;
       this.superViser = superViser;
       this.shifts = shifts;
       this.testType = testType;
       this.childQualities = childQualities;
    }
   
    public Integer getIdq() {
        return this.idq;
    }
    
    public void setIdq(Integer idq) {
        this.idq = idq;
    }
    public Superviser getSuperviser() {
        return this.superviser;
    }
    
    public void setSuperviser(Superviser superviser) {
        this.superviser = superviser;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public String getSuperViser() {
        return this.superViser;
    }
    
    public void setSuperViser(String superViser) {
        this.superViser = superViser;
    }
    public String getShifts() {
        return this.shifts;
    }
    
    public void setShifts(String shifts) {
        this.shifts = shifts;
    }
    public String getTestType() {
        return this.testType;
    }
    
    public void setTestType(String testType) {
        this.testType = testType;
    }
    public Set getChildQualities() {
        return this.childQualities;
    }
    
    public void setChildQualities(Set childQualities) {
        this.childQualities = childQualities;
    }




}


