package com.textile.model;
// Generated Apr 3, 2017 2:59:45 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ParentCarding generated by hbm2java
 */
public class ParentCarding  implements java.io.Serializable {


     private Integer idc;
     private Date date;
     private String shifts;
     private String superviser;
     private Float totalActualProduction;
     private Float totalExpectedProduction;
     private Float totalEfficiency;
     private Set childCardings = new HashSet(0);

    public ParentCarding() {
    }

    public ParentCarding(Date date, String shifts, String superviser, Float totalActualProduction, Float totalExpectedProduction, Float totalEfficiency, Set childCardings) {
       this.date = date;
       this.shifts = shifts;
       this.superviser = superviser;
       this.totalActualProduction = totalActualProduction;
       this.totalExpectedProduction = totalExpectedProduction;
       this.totalEfficiency = totalEfficiency;
       this.childCardings = childCardings;
    }
   
    public Integer getIdc() {
        return this.idc;
    }
    
    public void setIdc(Integer idc) {
        this.idc = idc;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public String getShifts() {
        return this.shifts;
    }
    
    public void setShifts(String shifts) {
        this.shifts = shifts;
    }
    public String getSuperviser() {
        return this.superviser;
    }
    
    public void setSuperviser(String superviser) {
        this.superviser = superviser;
    }
    public Float getTotalActualProduction() {
        return this.totalActualProduction;
    }
    
    public void setTotalActualProduction(Float totalActualProduction) {
        this.totalActualProduction = totalActualProduction;
    }
    public Float getTotalExpectedProduction() {
        return this.totalExpectedProduction;
    }
    
    public void setTotalExpectedProduction(Float totalExpectedProduction) {
        this.totalExpectedProduction = totalExpectedProduction;
    }
    public Float getTotalEfficiency() {
        return this.totalEfficiency;
    }
    
    public void setTotalEfficiency(Float totalEfficiency) {
        this.totalEfficiency = totalEfficiency;
    }
    public Set getChildCardings() {
        return this.childCardings;
    }
    
    public void setChildCardings(Set childCardings) {
        this.childCardings = childCardings;
    }




}


