package com.textile.model;
// Generated Apr 3, 2017 2:59:45 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ParentDrawing generated by hbm2java
 */
public class ParentDrawing  implements java.io.Serializable {


     private Integer idd;
     private Date date;
     private String superviser;
     private String shifts;
     private Float totalEp;
     private Float totalAp;
     private Float totalEfficiency;
     private Set childDrawings = new HashSet(0);

    public ParentDrawing() {
    }

    public ParentDrawing(Date date, String superviser, String shifts, Float totalEp, Float totalAp, Float totalEfficiency, Set childDrawings) {
       this.date = date;
       this.superviser = superviser;
       this.shifts = shifts;
       this.totalEp = totalEp;
       this.totalAp = totalAp;
       this.totalEfficiency = totalEfficiency;
       this.childDrawings = childDrawings;
    }
   
    public Integer getIdd() {
        return this.idd;
    }
    
    public void setIdd(Integer idd) {
        this.idd = idd;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public String getSuperviser() {
        return this.superviser;
    }
    
    public void setSuperviser(String superviser) {
        this.superviser = superviser;
    }
    public String getShifts() {
        return this.shifts;
    }
    
    public void setShifts(String shifts) {
        this.shifts = shifts;
    }
    public Float getTotalEp() {
        return this.totalEp;
    }
    
    public void setTotalEp(Float totalEp) {
        this.totalEp = totalEp;
    }
    public Float getTotalAp() {
        return this.totalAp;
    }
    
    public void setTotalAp(Float totalAp) {
        this.totalAp = totalAp;
    }
    public Float getTotalEfficiency() {
        return this.totalEfficiency;
    }
    
    public void setTotalEfficiency(Float totalEfficiency) {
        this.totalEfficiency = totalEfficiency;
    }
    public Set getChildDrawings() {
        return this.childDrawings;
    }
    
    public void setChildDrawings(Set childDrawings) {
        this.childDrawings = childDrawings;
    }




}


