package com.textile.model;
// Generated Apr 3, 2017 2:59:45 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ParentGdPrecleaning generated by hbm2java
 */
public class ParentGdPrecleaning  implements java.io.Serializable {


     private Integer idpr;
     private Date date;
     private String superviser;
     private String shifts;
     private String mixingNumber;
     private Integer issueNumber;
     private Float totalWeight;
     private Float totalMixing;
     private Float totalBales;
     private Set childGdPrecleanings = new HashSet(0);

    public ParentGdPrecleaning() {
    }

    public ParentGdPrecleaning(Date date, String superviser, String shifts, String mixingNumber, Integer issueNumber, Float totalWeight, Float totalMixing, Float totalBales, Set childGdPrecleanings) {
       this.date = date;
       this.superviser = superviser;
       this.shifts = shifts;
       this.mixingNumber = mixingNumber;
       this.issueNumber = issueNumber;
       this.totalWeight = totalWeight;
       this.totalMixing = totalMixing;
       this.totalBales = totalBales;
       this.childGdPrecleanings = childGdPrecleanings;
    }
   
    public Integer getIdpr() {
        return this.idpr;
    }
    
    public void setIdpr(Integer idpr) {
        this.idpr = idpr;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public String getSuperviser() {
        return this.superviser;
    }
    
    public void setSuperviser(String superviser) {
        this.superviser = superviser;
    }
    public String getShifts() {
        return this.shifts;
    }
    
    public void setShifts(String shifts) {
        this.shifts = shifts;
    }
    public String getMixingNumber() {
        return this.mixingNumber;
    }
    
    public void setMixingNumber(String mixingNumber) {
        this.mixingNumber = mixingNumber;
    }
    public Integer getIssueNumber() {
        return this.issueNumber;
    }
    
    public void setIssueNumber(Integer issueNumber) {
        this.issueNumber = issueNumber;
    }
    public Float getTotalWeight() {
        return this.totalWeight;
    }
    
    public void setTotalWeight(Float totalWeight) {
        this.totalWeight = totalWeight;
    }
    public Float getTotalMixing() {
        return this.totalMixing;
    }
    
    public void setTotalMixing(Float totalMixing) {
        this.totalMixing = totalMixing;
    }
    public Float getTotalBales() {
        return this.totalBales;
    }
    
    public void setTotalBales(Float totalBales) {
        this.totalBales = totalBales;
    }
    public Set getChildGdPrecleanings() {
        return this.childGdPrecleanings;
    }
    
    public void setChildGdPrecleanings(Set childGdPrecleanings) {
        this.childGdPrecleanings = childGdPrecleanings;
    }




}


