package com.textile.model;
// Generated Apr 3, 2017 2:59:45 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Powerunits generated by hbm2java
 */
public class Powerunits  implements java.io.Serializable {


     private Integer ide;
     private Date date;
     private String superviser;
     private String shifts;
     private Float blowRoom;
     private Float wrs;
     private Float prep;
     private Float oe1;
     private Float oe2;
     private Float oe3;
     private Float oe4;
     private Float oe5;
     private Float oe6;
     private Float hmPlant;
     private Float compressor;
     private Float lighting;
     private Float roPlant;
     private Float ycp;
     private Float balePress;
     private Float fireDump;
     private Float preCleaning;
     private Float total;

    public Powerunits() {
    }

    public Powerunits(Date date, String superviser, String shifts, Float blowRoom, Float wrs, Float prep, Float oe1, Float oe2, Float oe3, Float oe4, Float oe5, Float oe6, Float hmPlant, Float compressor, Float lighting, Float roPlant, Float ycp, Float balePress, Float fireDump, Float preCleaning, Float total) {
       this.date = date;
       this.superviser = superviser;
       this.shifts = shifts;
       this.blowRoom = blowRoom;
       this.wrs = wrs;
       this.prep = prep;
       this.oe1 = oe1;
       this.oe2 = oe2;
       this.oe3 = oe3;
       this.oe4 = oe4;
       this.oe5 = oe5;
       this.oe6 = oe6;
       this.hmPlant = hmPlant;
       this.compressor = compressor;
       this.lighting = lighting;
       this.roPlant = roPlant;
       this.ycp = ycp;
       this.balePress = balePress;
       this.fireDump = fireDump;
       this.preCleaning = preCleaning;
       this.total = total;
    }
   
    public Integer getIde() {
        return this.ide;
    }
    
    public void setIde(Integer ide) {
        this.ide = ide;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public String getSuperviser() {
        return this.superviser;
    }
    
    public void setSuperviser(String superviser) {
        this.superviser = superviser;
    }
    public String getShifts() {
        return this.shifts;
    }
    
    public void setShifts(String shifts) {
        this.shifts = shifts;
    }
    public Float getBlowRoom() {
        return this.blowRoom;
    }
    
    public void setBlowRoom(Float blowRoom) {
        this.blowRoom = blowRoom;
    }
    public Float getWrs() {
        return this.wrs;
    }
    
    public void setWrs(Float wrs) {
        this.wrs = wrs;
    }
    public Float getPrep() {
        return this.prep;
    }
    
    public void setPrep(Float prep) {
        this.prep = prep;
    }
    public Float getOe1() {
        return this.oe1;
    }
    
    public void setOe1(Float oe1) {
        this.oe1 = oe1;
    }
    public Float getOe2() {
        return this.oe2;
    }
    
    public void setOe2(Float oe2) {
        this.oe2 = oe2;
    }
    public Float getOe3() {
        return this.oe3;
    }
    
    public void setOe3(Float oe3) {
        this.oe3 = oe3;
    }
    public Float getOe4() {
        return this.oe4;
    }
    
    public void setOe4(Float oe4) {
        this.oe4 = oe4;
    }
    public Float getOe5() {
        return this.oe5;
    }
    
    public void setOe5(Float oe5) {
        this.oe5 = oe5;
    }
    public Float getOe6() {
        return this.oe6;
    }
    
    public void setOe6(Float oe6) {
        this.oe6 = oe6;
    }
    public Float getHmPlant() {
        return this.hmPlant;
    }
    
    public void setHmPlant(Float hmPlant) {
        this.hmPlant = hmPlant;
    }
    public Float getCompressor() {
        return this.compressor;
    }
    
    public void setCompressor(Float compressor) {
        this.compressor = compressor;
    }
    public Float getLighting() {
        return this.lighting;
    }
    
    public void setLighting(Float lighting) {
        this.lighting = lighting;
    }
    public Float getRoPlant() {
        return this.roPlant;
    }
    
    public void setRoPlant(Float roPlant) {
        this.roPlant = roPlant;
    }
    public Float getYcp() {
        return this.ycp;
    }
    
    public void setYcp(Float ycp) {
        this.ycp = ycp;
    }
    public Float getBalePress() {
        return this.balePress;
    }
    
    public void setBalePress(Float balePress) {
        this.balePress = balePress;
    }
    public Float getFireDump() {
        return this.fireDump;
    }
    
    public void setFireDump(Float fireDump) {
        this.fireDump = fireDump;
    }
    public Float getPreCleaning() {
        return this.preCleaning;
    }
    
    public void setPreCleaning(Float preCleaning) {
        this.preCleaning = preCleaning;
    }
    public Float getTotal() {
        return this.total;
    }
    
    public void setTotal(Float total) {
        this.total = total;
    }




}


