package com.textile.model;
// Generated Apr 3, 2017 2:59:45 PM by Hibernate Tools 4.3.1



/**
 * ProductsSample generated by hbm2java
 */
public class ProductsSample  implements java.io.Serializable {


     private Integer idl;
     private String productName;
     private String partialType;

    public ProductsSample() {
    }

    public ProductsSample(String productName, String partialType) {
       this.productName = productName;
       this.partialType = partialType;
    }
   
    public Integer getIdl() {
        return this.idl;
    }
    
    public void setIdl(Integer idl) {
        this.idl = idl;
    }
    public String getProductName() {
        return this.productName;
    }
    
    public void setProductName(String productName) {
        this.productName = productName;
    }
    public String getPartialType() {
        return this.partialType;
    }
    
    public void setPartialType(String partialType) {
        this.partialType = partialType;
    }




}


