/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.textile.model;

/**
 *
 * @author Masrat
 */


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ParentOpenend generated by hbm2java
 */
public class ReadyToPack  implements java.io.Serializable {


     private Integer ido;
     private Date date;
     private Integer count;
     private Float openingStockKgs;
     private Float packedbagsKgs;
     private Float readytopackKgs;
    
    
    public ReadyToPack() {
    }

    public ReadyToPack(Integer ido, Date date, Integer count, Float openingStockKgs, Float packedbagsKgs, Float readytopackKgs) {
        this.ido = ido;
        this.date = date;
        this.count = count;
        this.openingStockKgs = openingStockKgs;
        this.packedbagsKgs = packedbagsKgs;
        this.readytopackKgs = readytopackKgs;
    }
    

    public Integer getIdo() {
        return ido;
    }

    public void setIdo(Integer ido) {
        this.ido = ido;
    }

    public Date getDate() {
        return date;
    }

    public void setDate(Date date) {
        this.date = date;
    }

    public Integer getCount() {
        return count;
    }

    public void setCount(Integer count) {
        this.count = count;
    }

    public Float getOpeningStockKgs() {
        return openingStockKgs;
    }

    public void setOpeningStockKgs(Float openingStockKgs) {
        this.openingStockKgs = openingStockKgs;
    }

    public Float getPackedbagsKgs() {
        return packedbagsKgs;
    }

    public void setPackedbagsKgs(Float packedbagsKgs) {
        this.packedbagsKgs = packedbagsKgs;
    }

    public Float getReadytopackKgs() {
        return readytopackKgs;
    }

    public void setReadytopackKgs(Float readytopackKgs) {
        this.readytopackKgs = readytopackKgs;
    }

    



}



