package com.textile.model;
// Generated Apr 3, 2017 2:59:45 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Stock generated by hbm2java
 */
public class Stock  implements java.io.Serializable {


     private Integer ids;
     private Date date;
     private String variety;
     private Float stockQuantity;
     private Float stockKgs;
     private Float stockAvg;

    public Stock() {
    }

    public Stock(Date date, String variety, Float stockQuantity, Float stockKgs, Float stockAvg) {
       this.date = date;
       this.variety = variety;
       this.stockQuantity = stockQuantity;
       this.stockKgs = stockKgs;
       this.stockAvg = stockAvg;
    }
   
    public Integer getIds() {
        return this.ids;
    }
    
    public void setIds(Integer ids) {
        this.ids = ids;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public String getVariety() {
        return this.variety;
    }
    
    public void setVariety(String variety) {
        this.variety = variety;
    }
    public Float getStockQuantity() {
        return this.stockQuantity;
    }
    
    public void setStockQuantity(Float stockQuantity) {
        this.stockQuantity = stockQuantity;
    }
    public Float getStockKgs() {
        return this.stockKgs;
    }
    
    public void setStockKgs(Float stockKgs) {
        this.stockKgs = stockKgs;
    }
    public Float getStockAvg() {
        return this.stockAvg;
    }
    
    public void setStockAvg(Float stockAvg) {
        this.stockAvg = stockAvg;
    }




}


