package com.textile.model;
// Generated Apr 3, 2017 2:59:45 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * StockReportA generated by hbm2java
 */
public class StockReportA  implements java.io.Serializable {


     private Integer ids;
     private Date date;
     private String variety;
     private Float receivedQuantity;
     private Float receivedKgs;
     private Float receivedAvg;
     private Float issuepQuantity;
     private Float issuepKgs;
     private Float issuepAvg;
     private Float issuedQuantity;
     private Float issuedKgs;
     private Float issuedAvg;
     private Float saleQuantity;
     private Float saleKgs;
     private Float saleAvg;
     private Float stockQuantity;
     private Float stockKgs;
     private Float stockAvg;

    public StockReportA() {
    }

    public StockReportA(Date date, String variety, Float receivedQuantity, Float receivedKgs, Float receivedAvg, Float issuepQuantity, Float issuepKgs, Float issuepAvg, Float issuedQuantity, Float issuedKgs, Float issuedAvg, Float saleQuantity, Float saleKgs, Float saleAvg, Float stockQuantity, Float stockKgs, Float stockAvg) {
       this.date = date;
       this.variety = variety;
       this.receivedQuantity = receivedQuantity;
       this.receivedKgs = receivedKgs;
       this.receivedAvg = receivedAvg;
       this.issuepQuantity = issuepQuantity;
       this.issuepKgs = issuepKgs;
       this.issuepAvg = issuepAvg;
       this.issuedQuantity = issuedQuantity;
       this.issuedKgs = issuedKgs;
       this.issuedAvg = issuedAvg;
       this.saleQuantity = saleQuantity;
       this.saleKgs = saleKgs;
       this.saleAvg = saleAvg;
       this.stockQuantity = stockQuantity;
       this.stockKgs = stockKgs;
       this.stockAvg = stockAvg;
    }
   
    public Integer getIds() {
        return this.ids;
    }
    
    public void setIds(Integer ids) {
        this.ids = ids;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public String getVariety() {
        return this.variety;
    }
    
    public void setVariety(String variety) {
        this.variety = variety;
    }
    public Float getReceivedQuantity() {
        return this.receivedQuantity;
    }
    
    public void setReceivedQuantity(Float receivedQuantity) {
        this.receivedQuantity = receivedQuantity;
    }
    public Float getReceivedKgs() {
        return this.receivedKgs;
    }
    
    public void setReceivedKgs(Float receivedKgs) {
        this.receivedKgs = receivedKgs;
    }
    public Float getReceivedAvg() {
        return this.receivedAvg;
    }
    
    public void setReceivedAvg(Float receivedAvg) {
        this.receivedAvg = receivedAvg;
    }
    public Float getIssuepQuantity() {
        return this.issuepQuantity;
    }
    
    public void setIssuepQuantity(Float issuepQuantity) {
        this.issuepQuantity = issuepQuantity;
    }
    public Float getIssuepKgs() {
        return this.issuepKgs;
    }
    
    public void setIssuepKgs(Float issuepKgs) {
        this.issuepKgs = issuepKgs;
    }
    public Float getIssuepAvg() {
        return this.issuepAvg;
    }
    
    public void setIssuepAvg(Float issuepAvg) {
        this.issuepAvg = issuepAvg;
    }
    public Float getIssuedQuantity() {
        return this.issuedQuantity;
    }
    
    public void setIssuedQuantity(Float issuedQuantity) {
        this.issuedQuantity = issuedQuantity;
    }
    public Float getIssuedKgs() {
        return this.issuedKgs;
    }
    
    public void setIssuedKgs(Float issuedKgs) {
        this.issuedKgs = issuedKgs;
    }
    public Float getIssuedAvg() {
        return this.issuedAvg;
    }
    
    public void setIssuedAvg(Float issuedAvg) {
        this.issuedAvg = issuedAvg;
    }
    public Float getSaleQuantity() {
        return this.saleQuantity;
    }
    
    public void setSaleQuantity(Float saleQuantity) {
        this.saleQuantity = saleQuantity;
    }
    public Float getSaleKgs() {
        return this.saleKgs;
    }
    
    public void setSaleKgs(Float saleKgs) {
        this.saleKgs = saleKgs;
    }
    public Float getSaleAvg() {
        return this.saleAvg;
    }
    
    public void setSaleAvg(Float saleAvg) {
        this.saleAvg = saleAvg;
    }
    public Float getStockQuantity() {
        return this.stockQuantity;
    }
    
    public void setStockQuantity(Float stockQuantity) {
        this.stockQuantity = stockQuantity;
    }
    public Float getStockKgs() {
        return this.stockKgs;
    }
    
    public void setStockKgs(Float stockKgs) {
        this.stockKgs = stockKgs;
    }
    public Float getStockAvg() {
        return this.stockAvg;
    }
    
    public void setStockAvg(Float stockAvg) {
        this.stockAvg = stockAvg;
    }




}


