package com.readymix.model;
// Generated Aug 17, 2017 10:31:58 AM by Hibernate Tools 4.3.1



/**
 * Gst generated by hbm2java
 */
public class Gst  implements java.io.Serializable {


     private Integer gstid;
     private String gstNumber;

    public Gst() {
    }

    public Gst(String gstNumber) {
       this.gstNumber = gstNumber;
    }
   
    public Integer getGstid() {
        return this.gstid;
    }
    
    public void setGstid(Integer gstid) {
        this.gstid = gstid;
    }
    public String getGstNumber() {
        return this.gstNumber;
    }
    
    public void setGstNumber(String gstNumber) {
        this.gstNumber = gstNumber;
    }




}


