/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.textile.dto;

/**
 *
 * @author Masrat
 */
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * ParentCarding generated by hbm2java
 */
public class PCarding  implements java.io.Serializable {


     private Integer id;
     private Integer idc;
     private String date;
     private String shifts;
     private String superviser;
     private Float totalActualProduction;
     private Float totalExpectedProduction;
     private Float totalEfficiency;
     private Set childCardings = new HashSet(0);
     private String dat;
     private List<String> carding;
     private List<Float> mcspeed;
     private List<Float> hank;
     private List<Float> mcrun;
     private List<Float> exp;
     private List<Float> act;
     private List<Float> effic;
     private List<String> brek;
     private List<String> remk;
     private List<Integer> emId;

    public Integer getIdc() {
        return idc;
    }

    public void setIdc(Integer idc) {
        this.idc = idc;
    }
     
     
    public PCarding() {
    }

    public PCarding(String date, String shifts, String superviser, Float totalActualProduction, Float totalExpectedProduction, Float totalEfficiency, Set childCardings) {
       this.date = date;
       this.shifts = shifts;
       this.superviser = superviser;
       this.totalActualProduction = totalActualProduction;
       this.totalExpectedProduction = totalExpectedProduction;
       this.totalEfficiency = totalEfficiency;
       this.childCardings = childCardings;
    }

    public List<Float> getMcrun() {
        return mcrun;
    }

    public void setMcrun(List<Float> mcrun) {
        this.mcrun = mcrun;
    }

    public List<Float> getExp() {
        return exp;
    }

    public void setExp(List<Float> exp) {
        this.exp = exp;
    }

    public List<Float> getAct() {
        return act;
    }

    public void setAct(List<Float> act) {
        this.act = act;
    }

    public List<Float> getEffic() {
        return effic;
    }

    public void setEffic(List<Float> effic) {
        this.effic = effic;
    }

    public List<String> getBrek() {
        return brek;
    }

    public void setBrek(List<String> brek) {
        this.brek = brek;
    }

    public List<String> getRemk() {
        return remk;
    }

    public void setRemk(List<String> remk) {
        this.remk = remk;
    }
    

    public List<String> getCarding() {
        return carding;
    }

    public void setCarding(List<String> carding) {
        this.carding = carding;
    }

    public List<Float> getHank() {
        return hank;
    }

    public void setHank(List<Float> hank) {
        this.hank = hank;
    }

    public List<Float> getMcspeed() {
        return mcspeed;
    }

    public void setMcspeed(List<Float> mcspeed) {
        this.mcspeed = mcspeed;
    }


    

    public String getDat() {
        return dat;
    }

    public void setDat(String dat) {
        this.dat = dat;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getDate() {
        return this.date;
    }
    
    public void setDate(String date) {
        this.date = date;
    }
    public String getShifts() {
        return this.shifts;
    }
    
    public void setShifts(String shifts) {
        this.shifts = shifts;
    }

    public String getSuperviser() {
        return superviser;
    }

    public void setSuperviser(String superviser) {
        this.superviser = superviser;
    }
    
    public Float getTotalActualProduction() {
        return this.totalActualProduction;
    }
    
    public void setTotalActualProduction(Float totalActualProduction) {
        this.totalActualProduction = totalActualProduction;
    }
    public Float getTotalExpectedProduction() {
        return this.totalExpectedProduction;
    }
    
    public void setTotalExpectedProduction(Float totalExpectedProduction) {
        this.totalExpectedProduction = totalExpectedProduction;
    }
    public Float getTotalEfficiency() {
        return this.totalEfficiency;
    }
    
    public void setTotalEfficiency(Float totalEfficiency) {
        this.totalEfficiency = totalEfficiency;
    }
    public Set getChildCardings() {
        return this.childCardings;
    }
    
    public void setChildCardings(Set childCardings) {
        this.childCardings = childCardings;
    }

    public List<Integer> getEmId() {
        return emId;
    }

    public void setEmId(List<Integer> emId) {
        this.emId = emId;
    }

   


}

