package com.readymix.model;
// Generated Jul 28, 2017 4:51:08 PM by Hibernate Tools 4.3.1



/**
 * Grades generated by hbm2java
 */
public class Grades  implements java.io.Serializable {


     private Integer gid;
     private String grade;
     private String uom;
     private Float basicRate;

    public Grades() {
    }

    public Grades(String grade, String uom, Float basicRate) {
       this.grade = grade;
       this.uom = uom;
       this.basicRate = basicRate;
    }
   
    public Integer getGid() {
        return this.gid;
    }
    
    public void setGid(Integer gid) {
        this.gid = gid;
    }
    public String getGrade() {
        return this.grade;
    }
    
    public void setGrade(String grade) {
        this.grade = grade;
    }
    public String getUom() {
        return this.uom;
    }
    
    public void setUom(String uom) {
        this.uom = uom;
    }
    public Float getBasicRate() {
        return this.basicRate;
    }
    
    public void setBasicRate(Float basicRate) {
        this.basicRate = basicRate;
    }




}


