package com.readymix.model;
// Generated Jul 28, 2017 4:51:08 PM by Hibernate Tools 4.3.1



/**
 * Uom generated by hbm2java
 */
public class Uom  implements java.io.Serializable {


     private Integer id;
     private String uom;
     private Float quantity;
     private Float basicVal;

    public Uom() {
    }

    public Uom(String uom, Float quantity, Float basicVal) {
       this.uom = uom;
       this.quantity = quantity;
       this.basicVal = basicVal;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getUom() {
        return this.uom;
    }
    
    public void setUom(String uom) {
        this.uom = uom;
    }
    public Float getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(Float quantity) {
        this.quantity = quantity;
    }
    public Float getBasicVal() {
        return this.basicVal;
    }
    
    public void setBasicVal(Float basicVal) {
        this.basicVal = basicVal;
    }




}


