package com.readymix.model;
// Generated Jul 7, 2017 7:26:56 PM by Hibernate Tools 4.3.1



/**
 * Grades generated by hbm2java
 */
public class Grades  implements java.io.Serializable {


     private Integer gid;
     private String grade;
     private String uom;
     private Float basicRate;

    public String getUom() {
        return uom;
    }

    public void setUom(String uom) {
        this.uom = uom;
    }

    public Float getBasicRate() {
        return basicRate;
    }

    public void setBasicRate(Float basicRate) {
        this.basicRate = basicRate;
    }
     
     
     

    public Grades() {
    }

    public Grades(String grade) {
       this.grade = grade;
    }
   
    public Integer getGid() {
        return this.gid;
    }
    
    public void setGid(Integer gid) {
        this.gid = gid;
    }
    public String getGrade() {
        return this.grade;
    }
    
    public void setGrade(String grade) {
        this.grade = grade;
    }




}


